{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "242eb469-5951-4f7f-9781-755c757dfc3c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/pesu/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using device: cuda\n",
      "Loaded splits: 720 train, 140 val, 140 test video IDs\n",
      "\n",
      "── original (real) — 1000 videos ──\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "original:   1%|▍                              | 14/1000 [00:18<21:58,  1.34s/it]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mKeyboardInterrupt\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 210\u001b[39m\n\u001b[32m    206\u001b[39m             \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m  [\u001b[39m\u001b[38;5;132;01m{\u001b[39;00msplit\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m] \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mlabel\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mn\u001b[38;5;132;01m:\u001b[39;00m\u001b[33m,\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m    209\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[34m__name__\u001b[39m == \u001b[33m\"\u001b[39m\u001b[33m__main__\u001b[39m\u001b[33m\"\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m210\u001b[39m     \u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 190\u001b[39m, in \u001b[36mmain\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m    187\u001b[39m     \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[32m    189\u001b[39m out_dir = os.path.join(OUTPUT_ROOT, split, label)\n\u001b[32m--> \u001b[39m\u001b[32m190\u001b[39m saved, failed = \u001b[43mextract_from_video\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvideo_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mout_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvideo_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlabel\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    191\u001b[39m total_saved  += saved\n\u001b[32m    192\u001b[39m total_failed += failed\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 122\u001b[39m, in \u001b[36mextract_from_video\u001b[39m\u001b[34m(video_path, out_dir, video_id, label)\u001b[39m\n\u001b[32m    119\u001b[39m failed = \u001b[32m0\u001b[39m\n\u001b[32m    121\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m idx \u001b[38;5;129;01min\u001b[39;00m indices:\n\u001b[32m--> \u001b[39m\u001b[32m122\u001b[39m     \u001b[43mcap\u001b[49m\u001b[43m.\u001b[49m\u001b[43mset\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcv2\u001b[49m\u001b[43m.\u001b[49m\u001b[43mCAP_PROP_POS_FRAMES\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43midx\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    123\u001b[39m     ret, frame = cap.read()\n\u001b[32m    124\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m ret:\n",
      "\u001b[31mKeyboardInterrupt\u001b[39m: "
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "extract_faces.py\n",
    "────────────────\n",
    "MTCNN-based face extraction from FaceForensics++ videos.\n",
    "\n",
    "Usage:\n",
    "    python extract_faces.py\n",
    "\n",
    "Reads videos from:\n",
    "    ./face forensics/FaceForensics++_C23/{original,Deepfakes,Face2Face,FaceSwap,NeuralTextures}/\n",
    "\n",
    "Writes face crops (299×299 JPEGs) to:\n",
    "    ./dataset/{train,val,test}/{real,fake}/\n",
    "\n",
    "Uses the official FF++ JSON splits in ./splits/\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import json\n",
    "import cv2\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "from facenet_pytorch import MTCNN\n",
    "import torch\n",
    "from tqdm import tqdm\n",
    "\n",
    "# ── Config ────────────────────────────────────────────────────────────────────\n",
    "VIDEO_ROOT   = \"./face forensics/FaceForensics++_C23\"\n",
    "OUTPUT_ROOT  = \"./dataset\"\n",
    "SPLITS_DIR   = \"./splits\"\n",
    "FRAMES_PER_VIDEO = 32\n",
    "MARGIN_PCT   = 0.30        # 30% bounding-box margin\n",
    "CONFIDENCE   = 0.90        # MTCNN detection confidence threshold\n",
    "IMAGE_SIZE   = 299\n",
    "SKIP_ENDS    = 0.05        # skip first and last 5% of frames (fade transitions)\n",
    "\n",
    "REAL_METHODS = [\"original\"]\n",
    "FAKE_METHODS = [\"Deepfakes\", \"Face2Face\", \"FaceSwap\", \"NeuralTextures\"]\n",
    "\n",
    "SPLITS_FILES = {\n",
    "    \"train\": os.path.join(SPLITS_DIR, \"train.json\"),\n",
    "    \"val\":   os.path.join(SPLITS_DIR, \"val.json\"),\n",
    "    \"test\":  os.path.join(SPLITS_DIR, \"test.json\"),\n",
    "}\n",
    "\n",
    "# ── Setup ─────────────────────────────────────────────────────────────────────\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "print(f\"Using device: {device}\")\n",
    "\n",
    "mtcnn = MTCNN(\n",
    "    image_size=IMAGE_SIZE,\n",
    "    margin=0,               # we apply margin manually for control\n",
    "    min_face_size=40,\n",
    "    thresholds=[0.6, 0.7, 0.9],\n",
    "    factor=0.709,\n",
    "    keep_all=False,         # largest face only\n",
    "    device=device,\n",
    "    post_process=False,     # return raw pixels, not whitened\n",
    ")\n",
    "\n",
    "for split in [\"train\", \"val\", \"test\"]:\n",
    "    for label in [\"real\", \"fake\"]:\n",
    "        Path(os.path.join(OUTPUT_ROOT, split, label)).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "\n",
    "def load_splits():\n",
    "    \"\"\"Return dict: video_id (str) → split name.\"\"\"\n",
    "    id_to_split = {}\n",
    "    for split, path in SPLITS_FILES.items():\n",
    "        if not os.path.exists(path):\n",
    "            raise FileNotFoundError(f\"Split file not found: {path}\")\n",
    "        with open(path) as f:\n",
    "            pairs = json.load(f)\n",
    "        # FF++ splits are lists of [id_a, id_b] pairs\n",
    "        for pair in pairs:\n",
    "            for vid_id in pair:\n",
    "                id_to_split[str(vid_id).zfill(3)] = split\n",
    "    return id_to_split\n",
    "\n",
    "\n",
    "def add_margin(box, margin_pct, frame_w, frame_h):\n",
    "    \"\"\"Expand a bounding box by margin_pct on each side, clamped to frame.\"\"\"\n",
    "    x1, y1, x2, y2 = box\n",
    "    w = x2 - x1\n",
    "    h = y2 - y1\n",
    "    mx = int(w * margin_pct)\n",
    "    my = int(h * margin_pct)\n",
    "    x1 = max(0, int(x1) - mx)\n",
    "    y1 = max(0, int(y1) - my)\n",
    "    x2 = min(frame_w, int(x2) + mx)\n",
    "    y2 = min(frame_h, int(y2) + my)\n",
    "    return x1, y1, x2, y2\n",
    "\n",
    "\n",
    "def sample_frame_indices(total_frames, n=FRAMES_PER_VIDEO, skip=SKIP_ENDS):\n",
    "    \"\"\"Uniformly sample n frame indices, skipping the first/last skip fraction.\"\"\"\n",
    "    start = int(total_frames * skip)\n",
    "    end   = int(total_frames * (1 - skip))\n",
    "    if end - start < n:\n",
    "        start = 0\n",
    "        end   = total_frames\n",
    "    indices = np.linspace(start, end - 1, n, dtype=int)\n",
    "    return indices.tolist()\n",
    "\n",
    "\n",
    "def extract_from_video(video_path, out_dir, video_id, label):\n",
    "    \"\"\"Extract FRAMES_PER_VIDEO face crops from one video. Returns (saved, failed).\"\"\"\n",
    "    cap = cv2.VideoCapture(str(video_path))\n",
    "    if not cap.isOpened():\n",
    "        return 0, 1\n",
    "\n",
    "    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
    "    if total == 0:\n",
    "        cap.release()\n",
    "        return 0, 1\n",
    "\n",
    "    indices = sample_frame_indices(total)\n",
    "    saved = 0\n",
    "    failed = 0\n",
    "\n",
    "    for idx in indices:\n",
    "        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            failed += 1\n",
    "            continue\n",
    "\n",
    "        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "        h, w = frame_rgb.shape[:2]\n",
    "\n",
    "        # Detect face bounding box\n",
    "        boxes, probs = mtcnn.detect(frame_rgb)\n",
    "        if boxes is None or probs[0] < CONFIDENCE:\n",
    "            failed += 1\n",
    "            continue\n",
    "\n",
    "        # Take the highest-confidence detection\n",
    "        best = int(np.argmax(probs))\n",
    "        box  = boxes[best]\n",
    "        x1, y1, x2, y2 = add_margin(box, MARGIN_PCT, w, h)\n",
    "\n",
    "        face = frame_rgb[y1:y2, x1:x2]\n",
    "        if face.size == 0:\n",
    "            failed += 1\n",
    "            continue\n",
    "\n",
    "        face_resized = cv2.resize(face, (IMAGE_SIZE, IMAGE_SIZE),\n",
    "                                  interpolation=cv2.INTER_AREA)\n",
    "        face_bgr = cv2.cvtColor(face_resized, cv2.COLOR_RGB2BGR)\n",
    "\n",
    "        fname = f\"{video_id}_frame{idx:05d}.jpg\"\n",
    "        out_path = os.path.join(out_dir, fname)\n",
    "        cv2.imwrite(out_path, face_bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])\n",
    "        saved += 1\n",
    "\n",
    "    cap.release()\n",
    "    return saved, failed\n",
    "\n",
    "\n",
    "# ── Main ──────────────────────────────────────────────────────────────────────\n",
    "def main():\n",
    "    id_to_split = load_splits()\n",
    "    print(f\"Loaded splits: {sum(v == 'train' for v in id_to_split.values())} train, \"\n",
    "          f\"{sum(v == 'val' for v in id_to_split.values())} val, \"\n",
    "          f\"{sum(v == 'test' for v in id_to_split.values())} test video IDs\")\n",
    "\n",
    "    total_saved  = 0\n",
    "    total_failed = 0\n",
    "\n",
    "    all_methods = [(m, \"real\") for m in REAL_METHODS] + \\\n",
    "                  [(m, \"fake\") for m in FAKE_METHODS]\n",
    "\n",
    "    for method, label in all_methods:\n",
    "        method_dir = os.path.join(VIDEO_ROOT, method)\n",
    "        if not os.path.exists(method_dir):\n",
    "            print(f\"[SKIP] Directory not found: {method_dir}\")\n",
    "            continue\n",
    "\n",
    "        videos = sorted(Path(method_dir).glob(\"*.mp4\"))\n",
    "        print(f\"\\n── {method} ({label}) — {len(videos)} videos ──\")\n",
    "\n",
    "        for video_path in tqdm(videos, desc=method):\n",
    "            # FF++ video filenames are like 000.mp4, 001.mp4 … 999.mp4\n",
    "            video_id = video_path.stem.split(\"_\")[0].zfill(3)\n",
    "            split    = id_to_split.get(video_id)\n",
    "            if split is None:\n",
    "                continue\n",
    "\n",
    "            out_dir = os.path.join(OUTPUT_ROOT, split, label)\n",
    "            saved, failed = extract_from_video(video_path, out_dir, video_id, label)\n",
    "            total_saved  += saved\n",
    "            total_failed += failed\n",
    "\n",
    "    print(f\"\\n{'─'*50}\")\n",
    "    print(f\"Extraction complete.\")\n",
    "    print(f\"  Faces saved : {total_saved:,}\")\n",
    "    print(f\"  Frames lost : {total_failed:,}  \"\n",
    "          f\"({100*total_failed/(total_saved+total_failed+1e-9):.1f}%)\")\n",
    "\n",
    "    # Print split counts\n",
    "    print(f\"\\nOutput counts:\")\n",
    "    for split in [\"train\", \"val\", \"test\"]:\n",
    "        for label in [\"real\", \"fake\"]:\n",
    "            d = os.path.join(OUTPUT_ROOT, split, label)\n",
    "            n = len(list(Path(d).glob(\"*.jpg\")))\n",
    "            print(f\"  [{split}] {label}: {n:,}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "980c7081-7842-4c13-9a7e-a1b2dc415769",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
